name: CI

on:
  push:
    branches: [ master, 'fix/**', 'ci/**' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, x86]
        configuration: [Release, ReleaseDLL, ReleaseDLLStaticDeps, Debug, DebugDLL]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Initialize submodules
        shell: cmd
        run: |
          git submodule init devel/libtasn1
          for /F "tokens=*" %%n IN ('git config submodule.devel/libtasn1.url') DO @(git clone -n --depth=1 %%n devel/libtasn1)
          git -C devel/libtasn1 config core.protectNTFS false
          git -C devel/libtasn1 config core.sparseCheckout true
          echo /* > devel\libtasn1\.git\info\sparse-checkout
          echo !/tests/ >> devel\libtasn1\.git\info\sparse-checkout
          git submodule absorbgitdirs devel/libtasn1
          git -C devel/libtasn1 reset --hard
          git submodule update --init --depth=1 devel/libtasn1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup VSYASM
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File SMP\setup_vsyasm.ps1

      - name: Fetch Dependencies
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          powershell -ExecutionPolicy Bypass -File SMP\download_deps.ps1

      - name: Build libgnutls
        shell: cmd
        run: |
          msbuild SMP\libgnutls.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /m /v:m

      - name: Upload Artifacts
        if: matrix.configuration == 'Release' || matrix.configuration == 'ReleaseDLLStaticDeps'
        uses: actions/upload-artifact@v4
        with:
          name: libgnutls-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            msvc/bin/
            msvc/lib/
            msvc/include/
          if-no-files-found: ignore
